_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.9.16
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.9.16
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
epochs:
    value: 300
l1_upper:
    value: 4
l2_lower:
    value: 4
l2_upper:
    value: 0
learning_rate:
    value: 0.11889877819315492
model_name:
    value: ANN_with_LIF_output
momentum:
    value: 0.5634336624500149
optimizer:
    value: SGD
recurrent:
    value: true
regularization:
    value: true
v1_upper:
    value: 4
v2_lower:
    value: 0.01
v2_upper:
    value: 3
zenke_actual:
    value: true
